### ISSUE TITLE
getusers missing config module

### ISSUE THREAD

**Issue by rjusselrelic** [kenahrens/newrelic-api-client-js#1]
Hey mate, 

Looks like the getusers needs to have the updated config module added as a variable.   I'll submit a pull request.  Or I would imagine it would be easier for you to just add
``
var config = require('config');
``

**Comment by kenahrens** [comment]
Whoops! Fixed in this commit: https://github.com/kenahrens/newrelic-api-client-js/commit/b80a46ec06ddac7984cc6142f8e0c3f6739cd2e3

**Comment by kenahrens** [comment]
Closing
